version: '3.0'

services:
  grafana:
    container_name: 'grafana-reporter-plugin'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    environment:
      - GF_LOG_LEVEL=debug
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-reporter-plugin
      - ./.config/database.db:/opt/reporter/database.db
      - ./provisioning:/etc/grafana/provisioning
